from dataclasses import dataclass


@dataclass
class GeneratedFile:
    """
    Represents one generated file generated by the Generator Agent.
    """

    path: str

    action: str

    content: str